### PR TITLE
First working changeset submit against Mapillary.com

### PR DESCRIPTION
**Pull request by peterneubauer**
We are working on approving and visualizing changesets on Mapillary.com but submit should be working now already (with the risk of me deleting things during the next days while migrating old changesets :)

### CODE REVIEW

**Comment by floscher** [comment]
@peterneubauer Thank you for the PR. Is the changeset-feature currently work in progress or are the changes in this pull request already ready to merge in your eyes?

But anyway, at the moment there are some unit tests failing:
```
org.openstreetmap.josm.plugins.mapillary.history.MapillaryRecordTest > commandTest FAILED
    java.lang.NullPointerException
        at org.openstreetmap.josm.plugins.mapillary.MapillaryImage.checkModified(MapillaryImage.java:139)
        at org.openstreetmap.josm.plugins.mapillary.MapillaryImage.stopMoving(MapillaryImage.java:134)
        at org.openstreetmap.josm.plugins.mapillary.history.commands.CommandMove.undo(CommandMove.java:42)
        at org.openstreetmap.josm.plugins.mapillary.history.MapillaryRecord.undo(MapillaryRecord.java:107)
        at org.openstreetmap.josm.plugins.mapillary.history.MapillaryRecordTest.commandTest(MapillaryRecordTest.java:77)
org.openstreetmap.josm.plugins.mapillary.history.MapillaryRecordTest > commandMoveTest FAILED
    java.lang.NullPointerException
        at org.openstreetmap.josm.plugins.mapillary.MapillaryImage.checkModified(MapillaryImage.java:139)
        at org.openstreetmap.josm.plugins.mapillary.MapillaryImage.stopMoving(MapillaryImage.java:134)
        at org.openstreetmap.josm.plugins.mapillary.history.commands.CommandMove.undo(CommandMove.java:42)
        at org.openstreetmap.josm.plugins.mapillary.history.MapillaryRecord.undo(MapillaryRecord.java:107)
        at org.openstreetmap.josm.plugins.mapillary.history.MapillaryRecordTest.commandMoveTest(MapillaryRecordTest.java:124)
org.openstreetmap.josm.plugins.mapillary.history.MapillaryRecordTest > commandTurnTest FAILED
    java.lang.NullPointerException
        at org.openstreetmap.josm.plugins.mapillary.MapillaryImage.checkModified(MapillaryImage.java:139)
        at org.openstreetmap.josm.plugins.mapillary.MapillaryImage.turn(MapillaryImage.java:148)
        at org.openstreetmap.josm.plugins.mapillary.history.commands.CommandTurn.undo(CommandTurn.java:36)
        at org.openstreetmap.josm.plugins.mapillary.history.MapillaryRecord.undo(MapillaryRecord.java:107)
        at org.openstreetmap.josm.plugins.mapillary.history.MapillaryRecordTest.commandTurnTest(MapillaryRecordTest.java:155)
org.openstreetmap.josm.plugins.mapillary.MapillaryAbstractImageTest > testIsModified FAILED
    java.lang.NullPointerException
        at org.openstreetmap.josm.plugins.mapillary.MapillaryImage.checkModified(MapillaryImage.java:139)
        at org.openstreetmap.josm.plugins.mapillary.MapillaryImage.turn(MapillaryImage.java:148)
        at org.openstreetmap.josm.plugins.mapillary.MapillaryAbstractImageTest.testIsModified(MapillaryAbstractImageTest.java:59)
```
It'd be good, if you could also do „Organize imports“ on the files in order to get rid of most of the Codacy issues. Ideally with the import settings from [our codeStyleSettings.xml](https://github.com/floscher/josm-mapillary-plugin/blob/master/.idea/codeStyleSettings.xml#L5-10).

Thanks for the improvements, I'll be looking into it in more detail in the next days and merge it when ready.

**Comment by peterneubauer** [comment]
@floscher the API is working, it's just not possible to see the changesets that you submitted on mapillary.com yet. So please test it out and give feedback - I'm sure the UI could be much nicer. BTW, do you think there is any way to get MapillaryJS into JOSM in a web view or so?

**Comment by floscher** [comment]
So I finally got around to review this. So far it looks good to me, moving pictures around and submitting that as a changeset works well. But I wasn't able to submit a changeset with rotated images. In that case the Submit-button simply does nothing. But I think that can be fixed later.
I'll merge the changes in the next few days and release a new version of the plugin as soon as JOSM 16.06 is released. It's currently delayed, because of the switch of the JOSM server to Ubuntu 16.04 over the weekend.

I think the UI is ok, at least for the moment. The most important change would be in my eyes to display something easy to grasp like e.g. `image 0pVsKoI6-PdGSEA0DLIvow rotated by -5° and moved 5 meters north` instead of `Image[key=0pVsKoI6-PdGSEA0DLIvow,lat=48,748486,lon=8,345637,ca=176,465160,location=null,user=floscher,capturedAt=1440179420360]`. But the rest is good for now from my perspective.

**Comment by peterneubauer** [comment]
Thanks a lot, maybe I missed something for the compass angle changes, feel
free to test it. The changesets do support angle changes submitting.

**Comment by floscher** [comment]
The code is now in `master` as f356ba23880638535fe4d62bba91d87e60620a6b...70cf18e1efcd3aae96d6e69aedb97b6908718954.
I'll open a separate issue for changesets with turned images not working.

**Comment by peterneubauer** [comment]
Thanks @floscher ! I just tested with a compass angle change - it's working as far as I can see?
java_openstreetmap_editor

**Comment by floscher** [comment]
Hmm, yes. It works now for me too. Strange, I tried it several times yesterday and it only worked with unrotated images.
Maybe this behaviour was caused by #10. I'm sure I also tried a session where I did not trigger #10, but somehow it might still have caused that.

**Pull request closed without merging**
